// Public values only; generated by shared/scripts/configure-public.cjs
window.COMMUNITY_CONFIG = Object.freeze({
  "supabaseUrl": "https://oiszuaeuyqmlciywsvob.supabase.co",
  "publishableKey": "sb_publishable_ggdaozdmMtdk5S-7f781Yg_fn0pv_nW"
});
