// Explicit allowlist: never serialize process.env or the entire .env file.
const fs = require('node:fs');
const path = require('node:path');
const { parseEnv } = require('node:util');
const root = path.resolve(__dirname, '../..');
const local = fs.existsSync(path.join(root, '.env'))
  ? parseEnv(fs.readFileSync(path.join(root, '.env'), 'utf8')) : {};
const supabaseUrl = process.env.SUPABASE_URL || local.SUPABASE_URL || '';
const publishableKey = process.env.SUPABASE_PUBLISHABLE_KEY || local.SUPABASE_PUBLISHABLE_KEY || '';
if (!/^https:\/\/[a-z0-9.-]+\/?$/i.test(supabaseUrl) || !/^sb_publishable_[A-Za-z0-9_-]+$/.test(publishableKey)) {
  throw new Error('Provide an HTTPS Supabase URL and a modern sb_publishable_ key. No values were written.');
}
fs.writeFileSync(path.join(root, 'shared/frontend/public-config.js'),
  '// Public values only; generated by shared/scripts/configure-public.cjs\nwindow.COMMUNITY_CONFIG = Object.freeze(' +
  JSON.stringify({ supabaseUrl, publishableKey }, null, 2) + ');\n');
console.log('Browser configuration generated using only the URL and publishable key.');
